### ISSUE TITLE
Xcode 13 Beta 5 error build

### ISSUE THREAD

**Issue by kuritatu18** [uber/mockolo#158]
When I run `swift build -c release` in Xcode 13, I get the following error.
I think it's a compatibility issue with swift-syntax due to the upgrade to Swift 5.5 in Xcode 13.

```
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-tools-support-core/Sources/TSCBasic/Await.swift:18:28: error: value of type '(@escaping (Result<T, ErrorType>) -> Void) -> Void' has no member 'get'
    return try await(body).get()
                    ~~~~~~ ^~~
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-tools-support-core/Sources/TSCBasic/FileSystem.swift:122:29: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol FileSystem: class {
                            ^~~~~
                            AnyObject
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-tools-support-core/Sources/TSCBasic/ObjectIdentifierProtocol.swift:14:43: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol ObjectIdentifierProtocol: class, Hashable {}
                                          ^~~~~
                                          AnyObject
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-tools-support-core/Sources/TSCBasic/OutputByteStream.swift:46:35: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol OutputByteStream: class, TextOutputStream {
                                  ^~~~~
                                  AnyObject
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:120:46: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
    let textSize = hasCustomText ? Int(cnode.range.length) : 0
                                       ~~~~~ ^~~~~
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:153:35: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
      let startOffset = Int(cnode.range.offset)
                            ~~~~~ ^~~~~
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:157:55: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
      let end = utf8.index(begin, offsetBy: Int(cnode.range.length))
                                                ~~~~~ ^~~~~
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-syntax/Sources/SwiftSyntax/RawSyntax.swift:873:32: error: value of type 'CSyntaxNode' (aka 'swiftparse_syntax_node_t') has no member 'range'
    let byteLength = Int(cnode.range.length)
                         ~~~~~ ^~~~~
/Users/TatsunoriKuri/Documents/kuritatu18/mockolo/.build/checkouts/swift-syntax/Sources/SwiftSyntax/SyntaxParser.swift:195:57: error: missing argument for parameter #3 in call
    let c_top = swiftparse_parse_string(c_parser, source)
                                                        ^
                                                        , <#Int#>
_InternalSwiftSyntaxParser.swiftparse_parse_string:1:13: note: 'swiftparse_parse_string' declared here
public func swiftparse_parse_string(_: swiftparse_parser_t!, _ source: UnsafePointer<CChar>!, _ len: Int) -> swiftparse_client_node_t!
```

**Comment by vburojevic** [comment]
I still have the same issue with Mockolo 1.5.0 on Xcode 13 running on latest Big Sur.

**Comment by EspressoCup** [comment]
> I still have the same issue with Mockolo 1.5.0 on Xcode 13 running on the latest Big Sur.
> @EspressoCup why was this closed? Should it work in 1.5.0?

It should be resolved on master. Feel free to reopen if that's not the case.
