### ISSUE TITLE
xcode 13.3 - fatal error - SwiftSyntax.ParserError 1

### ISSUE THREAD

**Issue by SredzinskiPatryk** [uber/mockolo#182]
`MockoloFramework/SourceParser.swift:103: Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.)`

I do receive that error after updating my Xcode to 13.3. I was working previously on 13.2.1

**Comment by ManuC2001** [comment]
same issue with brew installation.

 It's probably linked to the swift 5.6 compatibility (cf. Package.swift line 9)

I rebuild it from source code (option 4 in the installation doc) and removed this line in the Package.swift and solved the issue.

**Comment by uhooi** [comment]
What version of Mockolo is installed by Homebrew?
I am wondering if `1.7.0` also causes an error.

**Comment by psredzinski** [comment]
Yes it fails on 1.7.0

**Comment by bezoadam** [comment]
I have version `1.7.0` and have same issue with Xcode 13.3

**Comment by entaku0818** [comment]
I have same issue with Xcode 13.3.
Mockolo was installed by Mint.


```Mintfile
uber/mockolo@1.7.0
```

Below is the build log.

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make generate-mocks-with-mockolo
mint run mockolo --sourcedirs ./VoicyRecorder/ -d ./VoicyRecorderTests/Helper/Mock/MockResults.swift -i VoicyRecorder --mock-final --enable-args-history
Start...
["Process input mock files..."]
["Took", 5.900859832763672e-05]
["Process source files and generate an annotated/protocol map..."]
MockoloFramework/SourceParser.swift:103: Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.)
```

**Comment by szk2s** [comment]
I have same issue with Xcode 13.3. I'm using Mockolo v1.7.0 installed by Homebrew.

**Comment by psredzinski** [comment]
1.7.0 works on 13.3 when installed using MINT

**Comment by wickwirew** [comment]
Ran into the same issue. Worked if I cloned it and ran it locally. Reinstalling and building from source fixed it for me.
```
brew reinstall --build-from-source mockolo
```

**Comment by maxwellE** [comment]
I think this is an issue caused by brew and not the source code, can we open a ticket there and close this one?

**Comment by keshavgn** [comment]
Hi 
I have version `1.7.0` and Xcode 13.4.1, getting the same error

```
Start...
["Process input mock files..."]
["Took", 9.500980377197266e-05]
["Process source files and generate an annotated/protocol map..."]
MockoloFramework/SourceParser.swift:101: Fatal error: The operation couldn’t be completed. (SwiftSyntax.ParserError error 1.)
zsh: illegal hardware instruction  ./tools/mockolo -s ./Core/Sources/Model -d 
```
Please need your help. Thanks

**Comment by Solace-Studios** [comment]
Is there a link to the brew ticket?

**Comment by tinder-maxwellelliott** [comment]
> Is there a link to the brew ticket?

Feel free to make another, or even better make a PR to the brew formula

**Comment by huypq-1004** [comment]
For anyone who installs `mockolo` by Mint or Homebrew:
This happened by missing `lib_InternalSwiftSyntaxParser.dylib` come along with the `mockolo` released binary.
We need to fix how Mint and Homebrew install these files.

My workaround: 
Step 1: Download `tar.gz` binary zipped file from https://github.com/uber/mockolo/releases/tag/1.7.1
Step 2: Extract, and copy all the files in the extracted folder into the current installed folder.
For Mint: 
```
~/.mint/packages/github.com_uber_mockolo/build/<your_installed_version>/
```
For Homebrew:
```
/opt/homebrew/Cellar/mockolo/<your_installed_version>/bin
```

**Comment by fummicc1** [comment]
I think this error had already been fixed since `1.8.0`.

ref.
- brew side
   - https://github.com/Homebrew/homebrew-core/pull/116229
- mint side
    - https://github.com/yonaskolb/Mint/pull/248
    - https://github.com/yonaskolb/Mint/pull/253

please try updating mockolo to the latest (`1.8.1`) by running `brew upgrade mockolo` / `mint install uber/mockolo@1.8.1`.

**Comment by sidepelican** [comment]
Issues around `lib_InternalSwiftSyntaxParser.dylib` are soleved at version `2.0.0`
