### ISSUE TITLE
Cannot install with Mint

### ISSUE THREAD

**Issue by uhooi** [uber/mockolo#104]
When trying to install Mockolo with Mint, the following error occurs:

```
$ mint bootstrap
🌱 Cloning mockolo 1.1.5
🌱 Resolving package
🌱 Building package
[1/13] Compiling clibc libc.c
[2/13] Compiling SourceKit SourceKit.m
[3/14] Compiling atomic-counter.c
[4/14] Compiling Clang_C Clang_C.m
[5/14] Compiling SPMLibc libc.swift
[6/15] Compiling writer.c
[7/15] Compiling reader.c
[8/16] Compiling api.c
[9/16] Compiling parser.c
[10/16] Compiling emitter.c
[11/16] Compiling scanner.c
[12/17] Compiling SWXMLHash SWXMLHash.swift
[13/17] Compiling Basic Await.swift
[14/18] Compiling Yams Constructor.swift
[15/19] Compiling SPMUtility ArgumentParser.swift
[16/19] Compiling SourceKittenFramework ByteCount.swift
[17/19] Compiling SwiftSyntax AbsolutePosition.swift
[18/20] Archiving libSwiftSyntax.a
[19/20] Compiling MockoloFramework ClassModel.swift
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/ParserViaSwiftSyntax.swift:72:18: error: value of type 'SourceFileSyntax' has no member 'walk'
            node.walk(&treeVisitor)
            ~~~~ ^~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:576:10: error: overriding declaration requires an 'override' keyword
    func visit(_ node: ProtocolDeclSyntax) -> SyntaxVisitorContinueKind {
         ^
    override 
SwiftSyntax.SyntaxVisitor:190:15: note: overridden declaration is here
    open func visit(_ node: SwiftSyntax.ProtocolDeclSyntax) -> SwiftSyntax.SyntaxVisitorContinueKind
              ^
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:584:10: error: overriding declaration requires an 'override' keyword
    func visit(_ node: ClassDeclSyntax) -> SyntaxVisitorContinueKind {
         ^
    override 
SwiftSyntax.SyntaxVisitor:186:15: note: overridden declaration is here
    open func visit(_ node: SwiftSyntax.ClassDeclSyntax) -> SwiftSyntax.SyntaxVisitorContinueKind
              ^
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:599:10: error: overriding declaration requires an 'override' keyword
    func visit(_ node: ImportDeclSyntax) -> SyntaxVisitorContinueKind {
         ^
    override 
SwiftSyntax.SyntaxVisitor:222:15: note: overridden declaration is here
    open func visit(_ node: SwiftSyntax.ImportDeclSyntax) -> SwiftSyntax.SyntaxVisitorContinueKind
              ^
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:149:38: warning: cast from 'DeclSyntax' to unrelated type 'VariableDeclSyntax' always fails
        if let varMember = self.decl as? VariableDeclSyntax {
                           ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:156:46: warning: cast from 'DeclSyntax' to unrelated type 'FunctionDeclSyntax' always fails
        } else if let funcMember = self.decl as? FunctionDeclSyntax {
                                   ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:162:51: warning: cast from 'DeclSyntax' to unrelated type 'SubscriptDeclSyntax' always fails
        } else if let subscriptMember = self.decl as? SubscriptDeclSyntax {
                                        ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:168:46: warning: cast from 'DeclSyntax' to unrelated type 'InitializerDeclSyntax' always fails
        } else if let initMember = self.decl as? InitializerDeclSyntax {
                                   ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:174:45: warning: cast from 'DeclSyntax' to unrelated type 'AssociatedtypeDeclSyntax' always fails
        } else if let patMember = self.decl as? AssociatedtypeDeclSyntax {
                                  ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:178:44: warning: cast from 'DeclSyntax' to unrelated type 'TypealiasDeclSyntax' always fails
        } else if let taMember = self.decl as? TypealiasDeclSyntax {
                                 ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:182:49: warning: cast from 'DeclSyntax' to unrelated type 'IfConfigDeclSyntax' always fails
        } else if let ifMacroMember = self.decl as? IfConfigDeclSyntax {
                                      ~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:194:44: warning: cast from 'DeclSyntax' to unrelated type 'VariableDeclSyntax' always fails
            if let varMember = member.decl as? VariableDeclSyntax {
                               ~~~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:233:77: warning: cast from 'Syntax' to unrelated type 'MemberDeclListSyntax' always fails
            if let desc = cl.condition?.description, let list = cl.elements as? MemberDeclListSyntax {
                                                                ~~~~~~~~~~~ ^   ~~~~~~~~~~~~~~~~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:248:64: error: value of type 'IfConfigDeclSyntax' has no member 'offset'
        let macroModel = IfMacroModel(name: name, offset: self.offset, entities: subModels)
                                                          ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:372:52: error: value of type 'PatternBindingSyntax' has no member 'offset'
                                         offset: v.offset,
                                                 ~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:373:52: error: value of type 'PatternBindingSyntax' has no member 'length'
                                         length: v.length,
                                                 ~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:402:55: error: value of type 'SubscriptDeclSyntax' has no member 'offset'
                                         offset: self.offset,
                                                 ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:403:55: error: value of type 'SubscriptDeclSyntax' has no member 'length'
                                         length: self.length,
                                                 ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:430:50: error: value of type 'FunctionDeclSyntax' has no member 'offset'
                                    offset: self.offset,
                                            ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:431:50: error: value of type 'FunctionDeclSyntax' has no member 'length'
                                    length: self.length,
                                            ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:469:41: error: value of type 'InitializerDeclSyntax' has no member 'offset'
                           offset: self.offset,
                                   ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:470:41: error: value of type 'InitializerDeclSyntax' has no member 'length'
                           length: self.length,
                                   ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:486:40: error: value of type 'GenericParameterSyntax' has no member 'offset'
                          offset: self.offset,
                                  ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:487:40: error: value of type 'GenericParameterSyntax' has no member 'length'
                          length: self.length)
                                  ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:523:40: error: value of type 'FunctionParameterSyntax' has no member 'offset'
                          offset: self.offset,
                                  ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:524:40: error: value of type 'FunctionParameterSyntax' has no member 'length'
                          length: self.length)
                                  ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:540:44: error: value of type 'AssociatedtypeDeclSyntax' has no member 'offset'
                              offset: self.offset,
                                      ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:541:44: error: value of type 'AssociatedtypeDeclSyntax' has no member 'length'
                              length: self.length,
                                      ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:555:44: error: value of type 'TypealiasDeclSyntax' has no member 'offset'
                              offset: self.offset,
                                      ~~~~ ^~~~~~
/private/var/folders/8z/2fgw5gmd1s5dxg45xf_gxl1j3w9szh/T/mint/github.com_uber_mockolo/Sources/MockoloFramework/Parsers/ViaSwiftSyntax/SwiftSyntaxExtensions.swift:556:44: error: value of type 'TypealiasDeclSyntax' has no member 'length'
                              length: self.length,
                                      ~~~~ ^~~~~~
🌱 Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.14". Use --verbose to see full output
🌱  Failed to build mockolo 1.1.5 with SPM
```

How can I solve it?

---

### Versions

- Mint: 0.14.1
- Mockolo: 1.1.5

### Mintfile

```yaml:Mintfile
realm/SwiftLint@0.38.2
uber/mockolo@1.1.5
Carthage/Carthage@0.34.0
yonaskolb/xcodegen@2.13.0
mono0926/LicensePlist@2.12.0
```

### Environment Variables

- MINT_PATH: /Users/{user name}/.mint/lib
- MINT_LINK_PATH: /Users/{user name}/.mint/bin

**Comment by elsh** [comment]
resolved; see https://github.com/uber/mockolo/pull/103

**Comment by elsh** [comment]
https://github.com/uber/mockolo/releases/tag/1.2.0

**Comment by uhooi** [comment]
Works fine with Mockolo 1.2.0.
thx😊
